### ISSUE TITLE
Paste does not work on dom1 IE

### ISSUE THREAD

**Issue by isichei** [ministryofjustice/analytics-platform-ops#100]
For some reason you cannot paste stuff into R studio when accessing through internet explorer. Tried pasting text into the console, shell and script editor and none worked. Mozilla Firefox seems to work normally on dom1 so suggest for time being that the guidance recommends accessing the platform from Mozilla (if not already doing so)

**Comment by RobinL** [comment]
Migrating issues to https://github.com/ministryofjustice/analytics-platform/issues
