### ISSUE TITLE
File size upload limit in R Studio

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform-ops#32]
There is a 1Mb file size limit for users wishing to upload data into their home directory.  I'd recommend this being larger.  At the moment, until we make s3 use more intuitive, I'd suggest setting this quite high - perhaps 100Mb, if that's possible/technically sensible.

**Comment by kerin** [comment]
Fixed in f203bc1f43981a12982dac0a11255f8d4cc3d044
