### ISSUE TITLE
Add phanton js to R Studio image to allow kniting Word and PDF output that includes html output

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform-ops#38]
If you want to output e.g. a d3.js graphic in your Word or PDF output, the current way R Studio does this is using webshot - see the following error message

```
webshot::install_phantomjs()

tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
/bin/tar: Child returned status 2
/bin/tar: Error is not recoverable: exiting now
Error in webshot::install_phantomjs() :
Unable to install PhantomJS to any of these dirs: ~/bin,
In addition: Warning messages:
1: In utils::untar(zipfile) :
‘/bin/tar -jxf 'phantomjs-2.1.1-linux-x86_64.tar.bz2'’ returned error code 2
2: In file.copy(exec, destdir, overwrite = TRUE) :
problem copying phantomjs-2.1.1-linux-x86_64/bin/phantomjs to /home/robinl/bin/phantomjs: No such file or directory
```

**Comment by xoen** [comment]
I added [webshot/phantomjs](https://github.com/ministryofjustice/analytics-platform-rstudio/pull/6]) to the RStudio docker image. This is fixed but will require a re-deploy of RStudio for the user.

**Comment by xoen** [comment]
(I'm testing this on my other instance on alpha then close the case)

**Comment by xoen** [comment]
@RobinL I'm closed the case. Existing RStudio instances will still not have phantoms installed but as soon they're re-deployed generation of PDF/Doc files with JS should work 👍
