### ISSUE TITLE
libpng required for Gov. R style package 

### ISSUE THREAD

**Issue by willbowditch** [ministryofjustice/analytics-platform-ops#42]
https://github.com/ukgovdatascience/govstyle 

requires dependency `libpng`

```
/bin/bash: libpng-config: command not found
read.c:3:17: fatal error: png.h: No such file or directory
#include <png.h>
```

**Comment by kerin** [comment]
Fixed in [RStudio v1.2.2](https://github.com/ministryofjustice/analytics-platform-rstudio/releases/tag/v1.2.2)
