### ISSUE TITLE
Errors on login

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform-ops#51]
## What happened?

I visited `https://robinl-rstudio.tools.alpha.mojanalytics.xyz` or `https://paulhkelly-rstudio.tools.alpha.mojanalytics.xyz/s/0da29cfc78a31fa11a1e3/events/get_events`

and got a page

`getting: "{"error":{"code":6,"error":null,"message":"Invalid json-rpc request"}}"`

## Steps to reproduce the problem

This seems to be an intermittent problem - it happens occasionally when you access the platform having not accessed it for a while.  The error message is sometimes different - but it's always a short json message.

## Expected behaviour

I expected to get into the platform, or be shown the login screen.

To successfully get into the platform, you can go back to your root url (e.g. `https://robinl-rstudio.tools.alpha.mojanalytics.xyz` ) and it lets you in

**Comment by andyhd** [comment]
Resolved
